### ISSUE TITLE
Handle logging differently

### ISSUE THREAD

**Issue by noonien** [hlandau/portmap#1]
Hello!
Thanks for this library, it's really the only library on GH I can use for mapping ports.

The only issue I have is that it outputs logging to stdout, and there doesn't appear to be anything to disable or redirect it.

Or perhaps I'm missing something?

**Comment by hlandau** [comment]
Fixed by making logging quiet by default.

For future reference, logging can be configured by the portmap.Log xlog log site: https://godoc.org/github.com/hlandau/portmap#pkg-variables

See this interface: https://godoc.org/github.com/hlandau/xlog#Site
This allows you to set severity (which is now by default), redirect log output, etc.

**Comment by noonien** [comment]
Thanks!
